// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetDnsZonesZone {
    /**
     * Zone Identifier
     */
    id?: string;
    /**
     * Zone Name
     */
    name?: string;
    /**
     * Primary Nameservers assigned to the Zone. Managed by Hetzner.
     */
    ns?: string[];
    /**
     * Zone activeness
     */
    paused?: boolean;
    /**
     * Status of the zone. Supported values are:
     * 			*verified*: Zone is verified.
     * 			*failed*: Zone verification is failed.
     * 			*pending*: Verification is in progress
     */
    status?: string;
    /**
     * Zone Default TTL for zone records
     */
    ttl?: number;
}

export interface GetDnsZonesZoneArgs {
    /**
     * Zone Identifier
     */
    id?: pulumi.Input<string>;
    /**
     * Zone Name
     */
    name?: pulumi.Input<string>;
    /**
     * Primary Nameservers assigned to the Zone. Managed by Hetzner.
     */
    ns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Zone activeness
     */
    paused?: pulumi.Input<boolean>;
    /**
     * Status of the zone. Supported values are:
     * 			*verified*: Zone is verified.
     * 			*failed*: Zone verification is failed.
     * 			*pending*: Verification is in progress
     */
    status?: pulumi.Input<string>;
    /**
     * Zone Default TTL for zone records
     */
    ttl?: pulumi.Input<number>;
}
