// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetDnsRecordsRecord {
    /**
     * Record Identifier
     */
    id: string;
    /**
     * Record name
     */
    name: string;
    /**
     * Record TTL
     */
    ttl: number;
    /**
     * Record Type. Supported values: [ A,AAAA,NS,MX,CNAME,RP,TXT,SOA,HINFO,SRV,DANE,TLSA,DS,CAA ]
     */
    type: string;
    /**
     * Record value
     */
    value: string;
    /**
     * Zone identifier that record belongs to
     */
    zoneId: string;
}

export interface GetDnsZonesZone {
    /**
     * Zone Identifier
     */
    id?: string;
    /**
     * Zone Name
     */
    name?: string;
    /**
     * Primary Nameservers assigned to the Zone. Managed by Hetzner.
     */
    ns: string[];
    /**
     * Zone activeness
     */
    paused: boolean;
    /**
     * Status of the zone. Supported values are:
     * 			*verified*: Zone is verified.
     * 			*failed*: Zone verification is failed.
     * 			*pending*: Verification is in progress
     */
    status: string;
    /**
     * Zone Default TTL for zone records
     */
    ttl: number;
}

