// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsZone extends pulumi.CustomResource {
    /**
     * Get an existing DnsZone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsZoneState, opts?: pulumi.CustomResourceOptions): DnsZone {
        return new DnsZone(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'hetzner:index/dnsZone:DnsZone';

    /**
     * Returns true if the given object is an instance of DnsZone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsZone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsZone.__pulumiType;
    }

    /**
     * Zone Name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Primary Nameservers assigned to the Zone. Managed by Hetzner.
     */
    public /*out*/ readonly ns!: pulumi.Output<string[]>;
    /**
     * Zone activeness
     */
    public /*out*/ readonly paused!: pulumi.Output<boolean>;
    /**
     * Status of the zone. Supported values are: *verified*: Zone is verified. *failed*: Zone verification is failed.
     * *pending*: Verification is in progress
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Zone Default TTL for zone records
     */
    public readonly ttl!: pulumi.Output<number>;

    /**
     * Create a DnsZone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsZoneArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsZoneArgs | DnsZoneState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsZoneState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["ns"] = state ? state.ns : undefined;
            resourceInputs["paused"] = state ? state.paused : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
        } else {
            const args = argsOrState as DnsZoneArgs | undefined;
            if ((!args || args.ttl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ttl'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
            resourceInputs["ns"] = undefined /*out*/;
            resourceInputs["paused"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsZone.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DnsZone resources.
 */
export interface DnsZoneState {
    /**
     * Zone Name
     */
    name?: pulumi.Input<string>;
    /**
     * Primary Nameservers assigned to the Zone. Managed by Hetzner.
     */
    ns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Zone activeness
     */
    paused?: pulumi.Input<boolean>;
    /**
     * Status of the zone. Supported values are: *verified*: Zone is verified. *failed*: Zone verification is failed.
     * *pending*: Verification is in progress
     */
    status?: pulumi.Input<string>;
    /**
     * Zone Default TTL for zone records
     */
    ttl?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a DnsZone resource.
 */
export interface DnsZoneArgs {
    /**
     * Zone Name
     */
    name?: pulumi.Input<string>;
    /**
     * Zone Default TTL for zone records
     */
    ttl: pulumi.Input<number>;
}
