// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("hetzner");

/**
 * Optional dns api enabler flag. DNS API is enabled by default.
 */
export declare const dnsApiEnabled: boolean | undefined;
Object.defineProperty(exports, "dnsApiEnabled", {
    get() {
        return __config.getObject<boolean>("dnsApiEnabled");
    },
    enumerable: true,
});

/**
 * Optional DNS Api Authentication token. When missing provider will populate it from `HETZNER_DNS_API_TOKEN` environment
 * variable.
 */
export declare const dnsApiToken: string | undefined;
Object.defineProperty(exports, "dnsApiToken", {
    get() {
        return __config.get("dnsApiToken");
    },
    enumerable: true,
});

