name: Deploy to HCloud

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (for Pulumi and Ansible)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Pulumi
      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      # Install Pulumi dependencies
      - name: Install Pulumi dependencies
        run: |
          pulumi plugin install resource hcloud v1.10.0


      # Install Ansible
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible


      # Configure Pulumi
      - name: Configure Pulumi
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login
          pulumi stack select temp-stack

      # Provision the server with Pulumi
      - name: Provision HCloud server
        run: pulumi up --yes

      # Get the server IP from Pulumi output
      # - name: Get server IP
      #   id: get-ip
      #   run: |
      #     IP=$(pulumi stack output serverIp)
      #     echo "::set-output name=server_ip::$IP"
      #
      # # Add the server IP to the Ansible inventory
      # - name: Create Ansible inventory
      #   run: |
      #     echo "[hcloud_server]" > inventory
      #     echo "${{ steps.get-ip.outputs.server_ip }}" >> inventory
      #
      # # Configure the server with Ansible
      # - name: Configure server with Ansible
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ansible-playbook -i inventory playbook.yml --user=root
      
      - name: Destroy HCloud server
        if: always()
        run: pulumi destroy --yes
